apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: arminferhat93/kub-demo-users-1:latest
          env:
            - name: AUTH_ADDRESS
            #  value: "10.98.204.2"
              value: "auth-service.default"